### ISSUE TITLE
Bio-Formats dependency imports

### ISSUE THREAD

**Issue by tischi** [tischi/fiji-plugin-plateViewer#6]
@sbesson @joshmoore

In order to get `loci.common.image.*` I needed to add this dependency:
```
<dependency>
	<groupId>org.openmicroscopy</groupId>
	<artifactId>ome-common</artifactId>
	<version>6.0.1</version>
</dependency>
```

See here:
- https://github.com/tischi/fiji-plugin-plateViewer/blob/master/pom.xml#L162

What confuses me is that you do not seem to need this dependency here:
- https://github.com/ome/bio-formats-examples/blob/master/pom.xml#L40

Do you know why that is?

**Comment by sbesson** [comment]
Hi @tischi, I tried to compile your project to reproduce your issues but failed at the following line:

```
sbesson@ls30630:fiji-plugin-plateViewer (master) $ mvn
...
[ERROR] Failed to execute goal on project fiji-plugin-plateViewer: Could not resolve dependencies for project org.scijava:fiji-plugin-plateViewer:jar:0.2.15: Could not find artifact de.embl.cba:bdv-utils:jar:0.2.10 in imagej.public (https://maven.imagej.net/content/groups/public) -> [Help 1]
```

Are all the dependencies available?

**Comment by tischi** [comment]
Could you please pull and try again?

**Comment by sbesson** [comment]
Now failing a bit further down the stack 

```
sbesson@ls30630:fiji-plugin-plateViewer (master) $ git pull
Already up to date.
sbesson@ls30630:fiji-plugin-plateViewer (master) $ mvn -Dmaven.repo.local=/tmp/.m2
...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:58 min
[INFO] Finished at: 2019-04-26T09:01:46+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project fiji-plugin-plateViewer: Could not resolve dependencies for project org.scijava:fiji-plugin-plateViewer:jar:0.2.15: Could not find artifact de.embl.cba:imaris-writer:jar:0.1.0 in imagej.public (https://maven.imagej.net/content/groups/public) -> [Help 1]
[ERROR] 
```

I might try and activate Travis on my fork - unless you want to activate it in your main repo to flag these failures .

**Comment by tischi** [comment]
Hi @sbesson, yeah, sorry, usually I am the only user of my repos...
Could you please try again now? Might be we need couple of more rounds...

**Comment by tischi** [comment]
> I might try and activate Travis on my fork - unless you want to activate it in your main repo to flag these failures .
If you tell me how to do this, I'd be happy to learn it!

**Comment by sbesson** [comment]
No problem at all, that happens as soon as you start having others building personal code :). For Travis, if you go to https://travis-ci.org/tischi/fiji-plugin-plateViewer, you should see an `Activate repository` which will create the integration.

From there, you should add a minimal top-level `.travis.yml` which will run the compilation and tests on every push

**Comment by tischi** [comment]
@sbesson OK, I will do! ...does it work now for you?

**Comment by sbesson** [comment]
I still fail to download `de.embl.cba:imaris-writer:jar:0.1.0`, I opened #7 with the minimal Travis configuration which should execute the default Maven command. https://travis-ci.com/tischi/fiji-plugin-plateViewer/builds/109733965 is reproducing the issue I am having locally

**Comment by tischi** [comment]
Hi @sbesson,

Thanks a lot for the travis.

I think it worked now: https://travis-ci.com/tischi/fiji-plugin-plateViewer/builds/109736407

**Comment by sbesson** [comment]
Great. Thanks for pushing the fixes. They certainly helped tracing the source of the issue. I think the problem comes from  these lines in`pom-scijava:25.0.0`: https://github.com/scijava/pom-scijava/blob/511ee941925309b143027f662d561069cded5fcd/pom.xml#L573-L575


```
		<!-- OME Common Java - https://github.com/ome/ome-common-java -->
		<ome-common.version>5.3.7</ome-common.version>
```

This is effectively overriding the version declared by the Bio-Formats 6.1.0-m1 POMs and pulling an older version of the `ome-common` dependency. An upstream release of `pom-scijava` with https://github.com/scijava/pom-scijava/pull/83 included might help although I know Curtis was resolving various dependencies.

Overriding this behavior as you did here should work to pull the version including the simple scaling utility in the interim.

**Comment by tischi** [comment]
OK. thanks! 
I'll close this issue then!
Looking forward to also learning the solutions to the other two issues!
